Faithful Scarlet Bobcat

Medium

# Users can only make one claim against a distribution even if they would be valid for multiple epochs.

### Summary

According to the devs in the discord, a user should be allowed to make separate claims against a distribution for different epochs. Design wise, this makes sense because it allows users to claim rewards as they become available. However, in practice, once a user makes a claim they will never be able to make another one because of the [claim.amount check](https://github.com/sherlock-audit/2024-10-gamma-rewarder/blob/475f7fbd0f7c2717ed585a67632e9a675b51c306/GammaRewarder/contracts/GammaRewarder.sol#L209) in handleProofResult().

### Root Cause

When a claim is handled, the amount already claimed is [checked to ensure that it is zero. Afterwards, it is set to whatever amount was claimed.](https://github.com/sherlock-audit/2024-10-gamma-rewarder/blob/475f7fbd0f7c2717ed585a67632e9a675b51c306/GammaRewarder/contracts/GammaRewarder.sol#L208-L214)

```solidity
        CumulativeClaim memory claim = claimed[userAddress][rewardTokenAddress][distributionId];
        require(claim.amount == 0 , "Already claimed reward.");


        claim.startBlock = startBlock;
        claim.endBlock = endBlock;
        claim.amount = totalRewardAmount;
        claimed[userAddress][rewardTokenAddress][distributionId] = claim;
```

The mapping that is updated is good for the entire distribution and makes no distinction between claims for different epochs, meaning that even if a user should be able to access rewards from another epoch, they will be locked out.

### Internal pre-conditions

_No response_

### External pre-conditions

_No response_

### Attack Path

_No response_

### Impact

Users that do not claim all of their rewards from a distribution in one transaction will be locked out of any remaining rewards, resulting in funds locked in the contract.

### PoC

Please but this in Audit.ts after Claim Test:

```solidity
  it("Double Claim", async function() {
    const testLpAddress = await users[10].getAddress()
    const distributionId = await rewardContract.getDistributionId(0)
    const amountPerEpoch = 4850000000000000000000n
    const rewardTokenAddress = await rewardToken.getAddress()
    let blocksPerEpoch = await rewardContract.blocksPerEpoch()
    let circuitOutput;


    // Add vkHash
    await rewardContract.addVkHash(VK_HASH)

    // claim for one epoch
    circuitOutput = _getCircuitOutput(
      testLpAddress, 
      hypervisor_address, 
      0, 
      start_block_num,
      start_block_num + blocksPerEpoch, 
      distributionId, 
      rewardTokenAddress, 
      amountPerEpoch, 
      1000
    )
    await rewardContract.claimTest(
      ethers.encodeBytes32String("string"),
      VK_HASH,
      circuitOutput
    )  

    // claim for the next epoch - it doesn't work
    // Error: VM Exception while processing transaction: reverted with reason string 'Already claimed reward.'
    try {
      circuitOutput = _getCircuitOutput(
        testLpAddress, 
        hypervisor_address, 
        0, 
        start_block_num + blocksPerEpoch,
        start_block_num + blocksPerEpoch + blocksPerEpoch, 
        distributionId, 
        rewardTokenAddress, 
        amountPerEpoch, 
        1000
      )
      await rewardContract.claimTest(
        ethers.encodeBytes32String("string"),
        VK_HASH,
        circuitOutput
      )  
    } catch (error) {console.log(`${error}`)}
  });
```

### Mitigation

_No response_